// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fibertrainee

const TableNameAccountDatum = "accountData"

// AccountDatum mapped from table <accountData>
type AccountDatum struct {
	Account  string `gorm:"column:account;not null" json:"account"`
	Password string `gorm:"column:password;not null" json:"password"`
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName AccountDatum's table name
func (*AccountDatum) TableName() string {
	return TableNameAccountDatum
}
